// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Lp1KsF4UupZPs38Y-Rkhu-NWgF5Er7Y',
    appId: '1:892410574641:web:0e20453de7454d5743a210',
    messagingSenderId: '892410574641',
    projectId: 'go90-6e83f',
    authDomain: 'go90-6e83f.firebaseapp.com',
    storageBucket: 'go90-6e83f.appspot.com',
    measurementId: 'G-SFL4YJCZDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVO9TFGCQ2IOROEPTmaJY1AlmQ8caA_Kk',
    appId: '1:892410574641:android:f1dd47d822b1968e43a210',
    messagingSenderId: '892410574641',
    projectId: 'go90-6e83f',
    storageBucket: 'go90-6e83f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNygsFyrSHGWSpz9UwFDER8urBJeh83hc',
    appId: '1:892410574641:ios:79d2b91149b57a6843a210',
    messagingSenderId: '892410574641',
    projectId: 'go90-6e83f',
    storageBucket: 'go90-6e83f.appspot.com',
    iosBundleId: 'com.example.groceryOnboardingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNygsFyrSHGWSpz9UwFDER8urBJeh83hc',
    appId: '1:892410574641:ios:79d2b91149b57a6843a210',
    messagingSenderId: '892410574641',
    projectId: 'go90-6e83f',
    storageBucket: 'go90-6e83f.appspot.com',
    iosBundleId: 'com.example.groceryOnboardingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Lp1KsF4UupZPs38Y-Rkhu-NWgF5Er7Y',
    appId: '1:892410574641:web:07a73d895b925b9343a210',
    messagingSenderId: '892410574641',
    projectId: 'go90-6e83f',
    authDomain: 'go90-6e83f.firebaseapp.com',
    storageBucket: 'go90-6e83f.appspot.com',
    measurementId: 'G-9GZP978KVQ',
  );

}