// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC60XSe3X1WhuuLiYXiypfWg15GXP9E4CA',
    appId: '1:863893854022:web:c94e010c0e633b554e7747',
    messagingSenderId: '863893854022',
    projectId: 'go90mart-aa4a8',
    authDomain: 'go90mart-aa4a8.firebaseapp.com',
    storageBucket: 'go90mart-aa4a8.appspot.com',
    measurementId: 'G-8SW4MMC6QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBafbnrugRbFzUWHMuWc_AaELlgi5dEks8',
    appId: '1:863893854022:android:60bf7aa48c042bc64e7747',
    messagingSenderId: '863893854022',
    projectId: 'go90mart-aa4a8',
    storageBucket: 'go90mart-aa4a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlxBKbhKvE8-S6XYB1T8nH8iHqNNlkGaM',
    appId: '1:863893854022:ios:f5ee549f8f90b17d4e7747',
    messagingSenderId: '863893854022',
    projectId: 'go90mart-aa4a8',
    storageBucket: 'go90mart-aa4a8.appspot.com',
    iosBundleId: 'com.example.groceryOnboardingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlxBKbhKvE8-S6XYB1T8nH8iHqNNlkGaM',
    appId: '1:863893854022:ios:d4d5f7ad47d4daa84e7747',
    messagingSenderId: '863893854022',
    projectId: 'go90mart-aa4a8',
    storageBucket: 'go90mart-aa4a8.appspot.com',
    iosBundleId: 'com.example.groceryOnboardingApp.RunnerTests',
  );
}
